# Generated by Django 5.0.2 on 2024-11-30 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networking_base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="contactduplicate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="emailaddress",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="googlecalendarevent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="googleemail",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="interactiontype",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="InteractionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topics_discussed",
                    models.JSONField(
                        default=list,
                        help_text="List of main topics identified in the interaction",
                    ),
                ),
                (
                    "action_items",
                    models.JSONField(
                        default=list,
                        help_text="List of action items extracted from the interaction",
                    ),
                ),
                (
                    "key_insights",
                    models.JSONField(
                        default=list,
                        help_text="Important points and insights from the interaction",
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        help_text="Sentiment score between -1 and 1", null=True
                    ),
                ),
                (
                    "follow_up_needed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this interaction needs follow-up",
                    ),
                ),
                (
                    "suggested_follow_up_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Recommended date for following up",
                        null=True,
                    ),
                ),
                (
                    "personal_info_mentioned",
                    models.JSONField(
                        default=dict,
                        help_text="Personal information mentioned during the interaction",
                    ),
                ),
                (
                    "conversation_context",
                    models.TextField(
                        blank=True,
                        help_text="Summary of how this interaction fits into the overall relationship",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this analysis was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this analysis was last updated"
                    ),
                ),
                (
                    "analysis_version",
                    models.CharField(
                        help_text="Version of the analysis model used", max_length=50
                    ),
                ),
                (
                    "interaction",
                    models.OneToOneField(
                        help_text="The interaction this analysis belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="networking_base.interaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "interaction analysis",
                "verbose_name_plural": "interaction analyses",
                "indexes": [
                    models.Index(
                        fields=["suggested_follow_up_date"],
                        name="analysis_followup_idx",
                    ),
                    models.Index(
                        fields=["follow_up_needed"], name="analysis_needsfollowup_idx"
                    ),
                    models.Index(
                        fields=["created_at", "last_updated"], name="analysis_dates_idx"
                    ),
                    models.Index(
                        fields=["sentiment_score"], name="analysis_sentiment_idx"
                    ),
                ],
            },
        ),
    ]
